spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    ups:
      master: 
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://172.30.16.49:3306/panta?characterEncoding=utf8
        username: root
        password: 123456
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://172.30.16.49:3306/panta?characterEncoding=utf8
        username: root
        password: 123456